name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [content-update]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v5

      - name: Print trigger info
        run: echo "Triggered by ${{ github.event.client_payload.source }}"

      - name: Prepare site inputs
        uses: ./.github/actions/prepare-site

      - name: Install, build, and upload your site
        uses: withastro/action@v5

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
